//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coastr {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppMessages() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Coastr.AppMessages", typeof(AppMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Deckel wurde bezahlt, ähnelt.
        /// </summary>
        internal static string MSG_COASTER_BILLED {
            get {
                return ResourceManager.GetString("MSG_COASTER_BILLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Um ein neuer Element hinzufügen ziehen sie einfach das + Symbol auf ein freies Feld ähnelt.
        /// </summary>
        internal static string MSG_HELP_ADD_COASTER_ITEM {
            get {
                return ResourceManager.GetString("MSG_HELP_ADD_COASTER_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Um ein Element komplett vom Deckel zu entfernen ziehen sie einfach das Symbol das Feld ähnelt.
        /// </summary>
        internal static string MSG_HELP_DELETE_COASTER_ITEM {
            get {
                return ResourceManager.GetString("MSG_HELP_DELETE_COASTER_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Um die Anzahl bestehender Elemente zu reduzieren ziehen sie einfach das - Symbol das Feld ähnelt.
        /// </summary>
        internal static string MSG_HELP_REMOVE_COASTER_ITEM {
            get {
                return ResourceManager.GetString("MSG_HELP_REMOVE_COASTER_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das ist bereits auf deinem Deckel. ähnelt.
        /// </summary>
        internal static string MSG_ITEM_ALREADY_IN_LIST {
            get {
                return ResourceManager.GetString("MSG_ITEM_ALREADY_IN_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das ist bereits auf der Speisekarte. ähnelt.
        /// </summary>
        internal static string MSG_ITEM_ALREADY_IN_VENUE {
            get {
                return ResourceManager.GetString("MSG_ITEM_ALREADY_IN_VENUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dieser Ort ist bereits bekannt ähnelt.
        /// </summary>
        internal static string MSG_LOCATION_ALREADY_KNOWN {
            get {
                return ResourceManager.GetString("MSG_LOCATION_ALREADY_KNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es sind keine Daten vorhanden ähnelt.
        /// </summary>
        internal static string MSG_NO_DATA {
            get {
                return ResourceManager.GetString("MSG_NO_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es wurde keine standart MAPS App auf dem Gerät gefunden. ähnelt.
        /// </summary>
        internal static string MSG_NO_MAPS_APP_FOUND {
            get {
                return ResourceManager.GetString("MSG_NO_MAPS_APP_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        internal static string MSG_OK {
            get {
                return ResourceManager.GetString("MSG_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Position konnte nicht ermittelt werden. Bitte prüfen sie die Einstellungen. ähnelt.
        /// </summary>
        internal static string MSG_POSITION_DISABLED {
            get {
                return ResourceManager.GetString("MSG_POSITION_DISABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Standort Neubestimmung... ähnelt.
        /// </summary>
        internal static string MSG_REFRESHING {
            get {
                return ResourceManager.GetString("MSG_REFRESHING", resourceCulture);
            }
        }
    }
}
